# Generated by Django 5.1.1 on 2024-11-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
