# Generated by Django 5.1.1 on 2024-11-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_vehicle_email_alter_vehicle_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('exited', 'Exited')], default='active', max_length=10),
        ),
    ]
