# Generated by Django 5.1.1 on 2024-11-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
